sudo: false
language: android
jdk:
    - oraclejdk8
android:
  components:
    # workaround to install latest platform-tools
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_script:
  - wget http://services.gradle.org/distributions/gradle-3.3-bin.zip
  - unzip -qq gradle-3.3-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
    - gradle build check
after_failure:
    - cat build/outputs/lint-results-devDebug.html
